"use client";

import React, { useRef, useEffect, useState } from "react";
import {
  ArrowUp,
  Loader2,
  Copy,
  Check,
  RotateCcw,
  FileText,
  Sparkles,
  ExternalLink,
} from "lucide-react";

export interface IDocumentSource {
  pageContent: string;
  metadata?: {
    pageNumber?: number | string;
    filename?: string;
    docId?: string;
    [key: string]: unknown;
  };
}

interface IMessage {
  id: string;
  role: "assistant" | "user";
  content: string;
  sources?: IDocumentSource[];
}

interface ChatComponentProps {
  activeDoc?: { docId: string; filename: string } | null;
}

/**
 * Strips trailing "Cited:\nPage X\nPage Y" or "Sources:\n..." blocks generated by LLM
 */
const stripTrailingCitations = (text: string): string => {
  if (!text) return "";
  return text
    // Multi-line trailing citations block
    .replace(
      /\n+\s*(?:Cited|Sources?\s*cited|Citations?|References?):?\s*(?:\n+\s*(?:[-*•]\s*)?(?:Page\s*\d+|Source\s*\d+|\d+)\s*)+$/i,
      ""
    )
    // Single-line trailing citations (e.g. "\nCited: Page 4, Page 1")
    .replace(
      /\n+\s*(?:Cited|Sources?\s*cited|Citations?|References?):?\s*(?:Page\s*\d+|Source\s*\d+|\d+)(?:[,\s]+(?:Page\s*\d+|Source\s*\d+|\d+))*\s*$/i,
      ""
    )
    .trim();
};

export const ChatComponent: React.FC<ChatComponentProps> = ({ activeDoc }) => {
  const [messages, setMessages] = useState<IMessage[]>([]);
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);
  const [copiedId, setCopiedId] = useState<string | null>(null);
  const [activeSnippet, setActiveSnippet] = useState<{ msgId: string; index: number } | null>(
    null
  );

  const messagesEndRef = useRef<HTMLDivElement>(null);
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages, loading]);

  useEffect(() => {
    if (textareaRef.current) {
      textareaRef.current.style.height = "auto";
      textareaRef.current.style.height = `${Math.min(textareaRef.current.scrollHeight, 160)}px`;
    }
  }, [input]);

  const copyAnswer = (text: string, id: string) => {
    const cleaned = stripTrailingCitations(text);
    navigator.clipboard.writeText(cleaned);
    setCopiedId(id);
    setTimeout(() => setCopiedId(null), 1800);
  };

  const handleSendMessage = async () => {
    const query = input.trim();
    if (!query || loading) return;

    setMessages((prev) => [
      ...prev,
      { id: crypto.randomUUID(), role: "user", content: query },
    ]);
    setInput("");
    if (textareaRef.current) textareaRef.current.style.height = "auto";
    setLoading(true);

    try {
      const params = new URLSearchParams({ message: query });
      if (activeDoc?.docId) {
        params.append("docId", activeDoc.docId);
      }

      const apiBase = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";
      const res = await fetch(`${apiBase}/chat?${params.toString()}`);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);

      const data = await res.json();
      setMessages((prev) => [
        ...prev,
        {
          id: crypto.randomUUID(),
          role: "assistant",
          content: data.answer || "No relevant information found in the document.",
          sources: Array.isArray(data.source) ? data.source : [],
        },
      ]);
    } catch {
      setMessages((prev) => [
        ...prev,
        {
          id: crypto.randomUUID(),
          role: "assistant",
          content: "Unable to reach the server. Please ensure the backend and Docker containers are running.",
        },
      ]);
    } finally {
      setLoading(false);
    }
  };

  /**
   * Renders inline tokens: interactive citation pills and bold markdown
   */
  const renderInlineTokens = (text: string, msgId: string, sources?: IDocumentSource[]) => {
    // Regex splits by either citation patterns OR bold text (**bold**)
    // Citation pattern is prioritized to avoid partial bold splits
    const INLINE_REGEX =
      /((?:\(\*\*|\[\*\*|\[|\(|\*\*)?\s*Source\s+\d+\s*(?:\||,|\-)\s*Page\s*[0-9a-zA-Z_-]+(?:\*\*\)|\*\*\]|\]|\)|\*\*)?|\*\*[^*]+?\*\*)/gi;

    const parts = text.split(INLINE_REGEX);

    return parts.map((part, pIdx) => {
      if (!part) return null;

      // Check if this part is a citation tag
      const citeMatch = part.match(
        /Source\s+(\d+)\s*(?:\||,|\-)\s*Page\s*([0-9a-zA-Z_-]+)/i
      );

      if (citeMatch && /Source\s+\d+/i.test(part)) {
        const sourceNum = parseInt(citeMatch[1], 10);
        const sourceIdx = sourceNum - 1;
        const pageNum = citeMatch[2].trim();
        const isSourceActive =
          activeSnippet?.msgId === msgId && activeSnippet.index === sourceIdx;

        return (
          <button
            key={`c-${pIdx}`}
            type="button"
            onClick={() => {
              if (sources && sources[sourceIdx]) {
                setActiveSnippet(isSourceActive ? null : { msgId, index: sourceIdx });
              }
            }}
            className={`inline-flex items-center gap-1 mx-1 px-1.5 py-0.5 rounded text-[11px] font-mono transition-all align-baseline cursor-pointer border ${
              isSourceActive
                ? "bg-zinc-900 text-white dark:bg-zinc-100 dark:text-zinc-950 border-zinc-900 dark:border-zinc-100 font-semibold shadow-xs"
                : "bg-emerald-50 dark:bg-emerald-950/50 hover:bg-emerald-100 dark:hover:bg-emerald-900/60 text-emerald-800 dark:text-emerald-300 border-emerald-200/80 dark:border-emerald-800/60"
            }`}
            title={`View verified excerpt from Source ${sourceNum} (Page ${pageNum})`}
          >
            <span>Source {sourceNum}</span>
            <span className="opacity-40">•</span>
            <span>P.{pageNum}</span>
          </button>
        );
      }

      // Check if bold (**bold text**)
      if (part.startsWith("**") && part.endsWith("**") && part.length > 4) {
        return (
          <strong key={`b-${pIdx}`} className="font-semibold text-zinc-900 dark:text-zinc-100">
            {part.slice(2, -2)}
          </strong>
        );
      }

      // Plain text
      return <span key={`t-${pIdx}`}>{part}</span>;
    });
  };

  /**
   * Formats raw markdown bullets (*, -), sub-bullets, and paragraphs cleanly
   */
  const renderFormattedAnswer = (content: string, msgId: string, sources?: IDocumentSource[]) => {
    const cleaned = stripTrailingCitations(content);
    const lines = cleaned.split("\n");

    return (
      <div className="space-y-2.5 text-[14px] leading-relaxed text-zinc-800 dark:text-zinc-200">
        {lines.map((line, lIdx) => {
          const trimmed = line.trim();
          if (!trimmed) return <div key={lIdx} className="h-1" />;

          // Subheadings (### or ##)
          if (trimmed.startsWith("### ") || trimmed.startsWith("## ")) {
            const headingText = trimmed.replace(/^#{2,3}\s+/, "");
            return (
              <h4
                key={lIdx}
                className="font-semibold text-zinc-900 dark:text-zinc-100 text-[14.5px] pt-2"
              >
                {renderInlineTokens(headingText, msgId, sources)}
              </h4>
            );
          }

          // Bullet points (* or -)
          const isBullet = /^\s*(\*|-)\s+/.test(line);
          const isNested = /^\s{2,}(\*|-)\s+/.test(line);

          if (isBullet) {
            const textToParse = line.replace(/^\s*(\*|-)\s+/, "");
            return (
              <div
                key={lIdx}
                className={`flex items-start gap-2.5 ${isNested ? "pl-5" : "pl-1.5"} py-0.5`}
              >
                <span className="text-zinc-400 dark:text-zinc-500 select-none text-xs leading-5 shrink-0">
                  {isNested ? "◦" : "•"}
                </span>
                <div className="flex-1 leading-relaxed">
                  {renderInlineTokens(textToParse, msgId, sources)}
                </div>
              </div>
            );
          }

          // Standard paragraph
          return (
            <p key={lIdx} className="leading-relaxed">
              {renderInlineTokens(trimmed, msgId, sources)}
            </p>
          );
        })}
      </div>
    );
  };

  return (
    <div className="flex flex-col h-full w-full bg-white dark:bg-[#0B0C0E] text-zinc-900 dark:text-zinc-100 font-sans">
      {/* Top Header */}
      <header className="h-12 border-b border-zinc-100 dark:border-zinc-800/60 px-6 flex items-center justify-between shrink-0 bg-transparent">
        <div className="flex items-center gap-2">
          {activeDoc ? (
            <div className="flex items-center gap-2 text-xs text-zinc-700 dark:text-zinc-200">
              <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
              <span className="font-medium truncate max-w-[200px] sm:max-w-md">
                {activeDoc.filename}
              </span>
              <span className="text-zinc-400 text-[11px] font-mono hidden sm:inline">• Active</span>
            </div>
          ) : (
            <div className="flex items-center gap-1.5 text-xs text-zinc-500 dark:text-zinc-400">
              <FileText className="w-3.5 h-3.5 text-zinc-400" />
              <span className="font-medium text-zinc-800 dark:text-zinc-200">DocBridge 2.0</span>
              <span className="text-zinc-400">• All Indexed Documents</span>
            </div>
          )}
        </div>

        <div className="flex items-center gap-3">
          {messages.length > 0 && (
            <button
              onClick={() => {
                setMessages([]);
                setActiveSnippet(null);
              }}
              className="flex items-center gap-1.5 text-xs text-zinc-400 hover:text-zinc-700 dark:hover:text-zinc-200 transition-colors"
            >
              <RotateCcw className="w-3.5 h-3.5" />
              <span>Reset</span>
            </button>
          )}
        </div>
      </header>

      {/* Messages Scroll Area */}
      <div className="flex-1 overflow-y-auto px-4 py-8 sm:px-8">
        <div className="max-w-2xl mx-auto space-y-8">
          {/* Calm, Clean Empty State */}
          {messages.length === 0 && (
            <div className="h-80 flex flex-col items-center justify-center text-center px-4 select-none">
              <div className="w-11 h-11 rounded-2xl bg-zinc-100 dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 flex items-center justify-center text-zinc-700 dark:text-zinc-300 mb-3.5 shadow-2xs">
                <Sparkles className="w-4 h-4" />
              </div>
              <div className="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full bg-zinc-100 dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 text-[10.5px] font-mono text-zinc-600 dark:text-zinc-400 mb-2.5">
                <span>DocBridge 2.0 Workspace</span>
              </div>
              <h3 className="text-sm sm:text-base font-semibold text-zinc-900 dark:text-zinc-100 mb-1.5">
                {activeDoc
                  ? `Ready to query ${activeDoc.filename}`
                  : "Grounded Document Intelligence"}
              </h3>
              <p className="text-xs text-zinc-500 dark:text-zinc-400 max-w-md leading-relaxed mb-6 font-normal">
                {activeDoc
                  ? "Ask targeted questions below to retrieve answers backed by hybrid dense-sparse retrieval and verified page citations."
                  : "Upload a PDF in the sidebar to start asking questions with page-level citations and zero hallucinations."}
              </p>

              {/* Quick suggestion chips (only when activeDoc is present) */}
              {activeDoc && (
                <div className="flex flex-wrap items-center justify-center gap-2 max-w-lg">
                  {[
                    "Summarize key findings & takeaways",
                    "What are the main risks or obligations?",
                    "Extract critical metrics and numbers",
                  ].map((suggestion, sIdx) => (
                    <button
                      key={sIdx}
                      type="button"
                      onClick={() => setInput(suggestion)}
                      className="text-xs px-3 py-1.5 rounded-lg border border-zinc-200 dark:border-zinc-800 bg-zinc-50/70 dark:bg-zinc-900/40 text-zinc-600 dark:text-zinc-400 hover:text-zinc-900 dark:hover:text-zinc-100 hover:border-zinc-300 dark:hover:border-zinc-700 hover:bg-zinc-100 dark:hover:bg-zinc-800/80 transition-all cursor-pointer shadow-2xs active:scale-[0.98]"
                    >
                      {suggestion}
                    </button>
                  ))}
                </div>
              )}
            </div>
          )}

          {/* Conversation Turns */}
          {messages.map((msg) => (
            <div key={msg.id} className="space-y-3">
              {msg.role === "user" ? (
                /* User Prompt (Right-aligned, clean dark pill) */
                <div className="flex justify-end">
                  <div className="bg-zinc-100 dark:bg-zinc-800/80 text-zinc-900 dark:text-zinc-100 rounded-2xl px-4 py-2.5 max-w-[85%] text-[13.5px] leading-relaxed shadow-2xs">
                    {msg.content}
                  </div>
                </div>
              ) : (
                /* Assistant Answer (Left-aligned, natural flowing prose) */
                <div className="space-y-3 text-[14px] leading-relaxed text-zinc-800 dark:text-zinc-200 pr-2">
                  {/* Formatted Answer with inline citation pills */}
                  {renderFormattedAnswer(msg.content, msg.id, msg.sources)}

                  {/* Sources Bar & Copy Action */}
                  <div className="pt-2 flex flex-wrap items-center justify-between gap-3 text-xs">
                    {/* Clear Source Buttons */}
                    {msg.sources && msg.sources.length > 0 ? (
                      <div className="flex flex-wrap items-center gap-1.5">
                        <span className="text-[11px] text-zinc-400 mr-1 flex items-center gap-1">
                          <FileText className="w-3 h-3 text-zinc-400" />
                          Cited Sources:
                        </span>
                        {msg.sources.map((src, idx) => {
                          const page = src.metadata?.pageNumber || "N/A";
                          const isActive =
                            activeSnippet?.msgId === msg.id && activeSnippet.index === idx;

                          return (
                            <button
                              key={idx}
                              onClick={() =>
                                setActiveSnippet(
                                  isActive ? null : { msgId: msg.id, index: idx }
                                )
                              }
                              className={`text-[11px] px-2.5 py-0.5 rounded font-mono transition-all border ${
                                isActive
                                  ? "bg-zinc-900 text-white dark:bg-zinc-100 dark:text-zinc-900 border-zinc-900 dark:border-zinc-100 font-semibold"
                                  : "bg-zinc-50 dark:bg-zinc-900 text-zinc-600 dark:text-zinc-400 border-zinc-200 dark:border-zinc-800 hover:border-zinc-300 dark:hover:border-zinc-700 hover:text-zinc-900 dark:hover:text-zinc-200"
                              }`}
                            >
                              Source {idx + 1} (Page {page})
                            </button>
                          );
                        })}
                      </div>
                    ) : (
                      <span />
                    )}

                    {/* Copy Button */}
                    <button
                      onClick={() => copyAnswer(msg.content, msg.id)}
                      className="text-[11px] text-zinc-400 hover:text-zinc-700 dark:hover:text-zinc-200 flex items-center gap-1 transition-colors"
                      title="Copy response"
                    >
                      {copiedId === msg.id ? (
                        <>
                          <Check className="w-3 h-3 text-emerald-500" />
                          <span>Copied</span>
                        </>
                      ) : (
                        <>
                          <Copy className="w-3 h-3" />
                          <span>Copy</span>
                        </>
                      )}
                    </button>
                  </div>

                  {/* Quoted Snippet Drawer (When a source button or inline citation is clicked) */}
                  {activeSnippet?.msgId === msg.id &&
                    msg.sources &&
                    msg.sources[activeSnippet.index] && (
                      <div className="mt-3 p-3.5 rounded-xl border border-emerald-200/80 dark:border-emerald-800/60 bg-emerald-50/30 dark:bg-emerald-950/20 text-xs space-y-1.5 animate-in fade-in-50 duration-150">
                        <div className="flex items-center justify-between">
                          <span className="font-mono text-[11px] font-semibold text-emerald-800 dark:text-emerald-300 flex items-center gap-1.5">
                            <FileText className="w-3.5 h-3.5" />
                            Source {activeSnippet.index + 1} • Page{" "}
                            {msg.sources[activeSnippet.index].metadata?.pageNumber || "N/A"}
                          </span>
                          <button
                            onClick={() => setActiveSnippet(null)}
                            className="text-[11px] text-zinc-400 hover:text-zinc-700 dark:hover:text-zinc-200"
                          >
                            Dismiss
                          </button>
                        </div>
                        <p className="font-mono text-[12px] leading-relaxed text-zinc-700 dark:text-zinc-300 whitespace-pre-wrap bg-white/80 dark:bg-zinc-900/60 p-3 rounded-lg border border-emerald-100 dark:border-emerald-900/40">
                          "{msg.sources[activeSnippet.index].pageContent}"
                        </p>
                      </div>
                    )}
                </div>
              )}
            </div>
          ))}

          {/* Minimal Loading Indicator */}
          {loading && (
            <div className="flex items-center gap-2 text-xs text-zinc-400 py-1">
              <Loader2 className="w-3.5 h-3.5 animate-spin text-zinc-400" />
              <span>Analyzing document and retrieving citations...</span>
            </div>
          )}

          <div ref={messagesEndRef} />
        </div>
      </div>

      {/* Input Footer Bar */}
      <div className="p-4 sm:p-6 bg-transparent shrink-0">
        <div className="max-w-2xl mx-auto flex flex-col gap-1.5">
          <div className="flex items-end border border-zinc-200 dark:border-zinc-800 rounded-2xl bg-zinc-50/70 dark:bg-zinc-900/60 px-4 py-2.5 focus-within:border-zinc-400 dark:focus-within:border-zinc-600 focus-within:ring-1 focus-within:ring-zinc-400/20 transition-all shadow-xs">
            <textarea
              ref={textareaRef}
              rows={1}
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === "Enter" && !e.shiftKey) {
                  e.preventDefault();
                  handleSendMessage();
                }
              }}
              placeholder={
                activeDoc
                  ? `Ask about ${activeDoc.filename}...`
                  : "Ask a question about your documents..."
              }
              className="w-full bg-transparent resize-none text-[13.5px] text-zinc-900 dark:text-zinc-100 placeholder:text-zinc-400 focus:outline-none leading-relaxed py-1"
              disabled={loading}
            />

            <button
              onClick={handleSendMessage}
              disabled={!input.trim() || loading}
              className="p-1.5 rounded-xl bg-zinc-900 dark:bg-zinc-100 text-white dark:text-zinc-950 disabled:opacity-20 hover:opacity-90 active:scale-95 transition-all ml-2 shrink-0 mb-0.5 cursor-pointer disabled:cursor-not-allowed"
              title="Send question"
            >
              <ArrowUp className="w-4 h-4" />
            </button>
          </div>

          <div className="flex items-center justify-between px-2 text-[10.5px] text-zinc-400 font-mono">
            <span>DocBridge 2.0 • Hybrid RAG</span>
            <span className="hidden sm:inline">↵ Send • Shift + ↵ New line</span>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ChatComponent;
